<?php

namespace frontend\controllers;

use common\components\CarCouponAction;
use common\components\CExcel;
use common\models\Car_paternalor;
use common\models\CarCoupon;
use common\models\CarCouponPackage;
use common\models\CarMobile;
use common\models\CarSubstituteDriving;
use common\models\ErrorLog;
use common\models\FansAccount;
use Yii;
use JMessage\JMessage;
use common\components\EDaiJia;
use frontend\util\PController;
use GuzzleHttp\Client;

class SimonController extends PController
{

    public function renderAjax($view, $params = [])
    {
        return parent::renderAjax($view, $params); // TODO: Change the autogenerated stub
    }

    public $site_title = '云车驾到';
    public $menuActive = 'caruorder';

    public function actionTest(){
        $cache = Yii::$app->cache;
        $key = "mobile_send_"."13937112203";
        $cache->set($key,0);
       $number = $cache->get($key);
        var_dump($number);


/*        $time = time();
        //过去二十分钟登录的，查一次，
        $old_time = $time-15*60;

        $users = FansAccount::find()
            ->select('tpy_fans_account.mobile,tpy_fans_account.uid,tpy_car_mobile.coupon_batch_no,tpy_car_mobile.id')
            ->rightJoin('tpy_car_mobile','tpy_car_mobile.mobile=tpy_fans_account.mobile')
            ->where(['>','tpy_fans_account.u_time', $old_time])
            ->andWhere(['tpy_car_mobile.uid'=>0])
            ->asArray()->all();
        var_dump($users);*/

    }

    public function actionShandong(){
        phpinfo();
    }









public function actionJiguang(){


    $appKey='236fdb518ca71b4a912c5567';
    $masterSecret='3e070ee1e7b9aa9f47ff363a';
    $jm = new JMessage($appKey, $masterSecret);
    print_r($jm);
}

/**
 * 鼎翰文化，彭亚南测试
 */
public function actionCeshi(){
    $user_auth = [
        'uid' => '4209',
        'nickname' => '鼎翰文化',
        'headimgurl' => 'http://www.yunche168.com/frontend/web/images/logo.jpg',
        'sex' => 0,
        'pid' => 0
    ];
    Yii::$app->session['wx_user_auth'] = $user_auth;
}

/**
 * 订单更新
 */
public function actionDriving(){

    $path = Yii::$app->getBasePath().'/web/log/driving.csv';

    $obj = new Car_paternalor();
    $model_Counpon = new CarCoupon();
    $model_driving = new CarSubstituteDriving();



    $handle = fopen($path, "r");

    $i = 0;
    while (($fileop = fgetcsv($handle, 1000, ",")) !== false) {
        if($i==0){
            $i=1;
            continue;
        }
        $coupon_no = mb_convert_encoding($fileop[1], "UTF-8", "GBK");
        $start_time = mb_convert_encoding($fileop[8], "UTF-8", "GBK");
        $start_time = strtotime($start_time);

        $end_time = mb_convert_encoding($fileop[9], "UTF-8", "GBK");
        $end_time = strtotime($end_time);

        $mobile = mb_convert_encoding($fileop[5], "UTF-8", "GBK");
        $start = mb_convert_encoding($fileop[10], "UTF-8", "GBK");
        $end = mb_convert_encoding($fileop[11], "UTF-8", "GBK");
        $remark = mb_convert_encoding($fileop[23], "UTF-8", "GBK");
        $order_id = mb_convert_encoding($fileop[2], "UTF-8", "GBK");



        $coupon_info = $model_Counpon->table()->where("coupon_sn=$coupon_no")->one();
        if(!$coupon_info){
            continue;
        }

        //根据优惠券查找订单，如果有，则跳过
        $coupon_id = $coupon_info['id'];
        $order_info = $model_driving->table()->where("coupon_id=$coupon_id and status in (304,501)")->one();
        if($order_info){
            continue;
        }
        $uid = $coupon_info['uid'];
        $order_no =$obj->create_order_no($uid, 'E');

        $data = [
            'order_no' => $order_no,
            'uid' => $uid,
            'type' => 2,
            'coupon_id' => $coupon_id,
            'coupon_amount' => $coupon_info['amount'],
            'c_time' => $start_time
        ];
        $id = $obj->myInsert($data);


        $data = [
            'uid' => $uid,
            'mobile' => $mobile,
            'coupon_id' => $coupon_id,
            'coupon_sn' => $coupon_no,
            'date_day' => date("Ymd",$start_time),
            'date_month' => date("Ym",$start_time),
            'm_id' => $id,
            'orderid' => $order_no,
            'departure' => $start,
            'status' => '501',
            'start_lat' => ' ',
            'start_lng' => ' ',
            'destination' => $end,
            'order_id' => $order_id,
            'end_lat' => ' ',
            'end_lng' =>' ',
            'start_time' => $start_time,
            'end_time' => $end_time,
            'booking_id' => 'append',
            'booking_type' => '01003',
            'estimated_cost' =>0,
            'company_id' =>0,
        ];
        $id = $model_driving->myInsert($data);
        if ($id) {
            $data['id'] = $id;
        }
        print($id);
        print("\n");

    }
}


public function actionDriver(){
    $e = new EDaiJia();

    $result = $e->getDriverInfo('JN56295');
    print_r($result);
}

public function actionOilinfo(){
    $this->layout = 'cloudcarv2';
    $request = Yii::$app->request;
    $id = $request->get('id', null);
    $info = (new CarOilor())->table()->where([ 'm_id' => $id])->one();
    if (!$info) {
        return '订单不存在';
    }
    $info['status_text'] = CarOilor::$status_text[(string)$info['status']];

    return $this->render('oilinfo', ['info' => $info]);
}



public function actionRedis(){
    $redis = Yii::$app->redis;
    $token_key =  'simontest_';
    $redis->set($token_key,'test');
    echo $redis->get($token_key);
}


public function actionInspection(){
    try{
        $diandian_oil = new DianDianInspection();

        $data =[];
        $data['cardNumber'] = '222222222';
        $data['money'] = 100;
        $data['rechargePhone'] = '13365802535';
        $result = $diandian_oil->vehicleAdd(1,$data);
        print_r($result);

        $data = [];
        $data['payMethod'] = 5;
        $data['orderId'] = 7951317;
        $data['payPrice'] = 108;
        $result = $diandian_oil->pay_pre(1,$data);
        print_r($result);



    }catch (\Exception $exception){
        echo $exception->getMessage();
    }
}


public function actionOil()
{

    try{

        $db = Yii::$app->db;
        $trans = $db->beginTransaction();
        $diandian_oil = new DianDianOilCard();


        $result = $diandian_oil->oil_card_list();
        print_r($result);
//            die();
//
        $data = [];
        $data['money']=50.00;
        $result = $diandian_oil->oil_card_instore($data);
        print_r($result);
//           throw new \Exception('aaa');

//
//
        $data =[];
        $data['cardNumber'] = '9030000005107514';
        $data['money'] = 100;
        $data['rechargePhone'] = '13365802535';
        $result = $diandian_oil->oil_recharge_1_1(1,$data);
        print_r($result);

        $data = [];
        $data['payMethod'] = 5;
        $data['orderId'] = 7951317;
        $data['payPrice'] = 108;
        $result = $diandian_oil->pay_pre(1,$data);
        print_r($result);
        $trans->commit();

    }catch (\Exception $exception){
        $trans->rollBack();
        echo $exception->getMessage();
    }
}


public function actionApi()
{
    $baseurl = Yii::$app->request->queryString;
    //对baseurl进行处理，把&符号前面的去掉
    $params =  strstr($baseurl,"&");
    $params = substr($params,1);


    $post_data = yii::$app->getRequest()->getRawBody();
    $diandian = new DianDian();
    $result = $diandian->checkToken($params,$post_data);
    Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
    if($result){

        return ['success'=>true];
//            return ['status' => $status,'msg' => $msg, 'data' => $data, 'url' => $url, 'waiting' => $waiting];
    }else{

        return ['success'=>false];
    }

}

public function actionBrand(){
    try{
        $diandian = new DianDianInspection();


        $result = $diandian->getBrandList();

//            $result = json_decode($result,true);
        foreach ($result as $item){
            print_r($item);
            $brand = new CarBrand();
            $brand->id = $item['brandId'];
            $brand->name = $item['brandName'];
            $brand->logo = $item['icon'];
            $brand->status = intval($item['isValid']);
            $brand->save();
            print_r('success!');
        }
        print_r($brand->id );

    }catch (\Exception $exception){
        echo $exception->getMessage();
    }
}

public function actionSeries()
{
    try{
        $diandian = new DianDianInspection();

        $brands = CarBrand::find()
//              ->where(['>', 'id', 140])
            ->orderBy('id')
            ->all();
        foreach($brands as $brand){
            $result = $diandian->getSerieslist($brand['id']);
            //添加到表
            print_r($brand->id );

//                $result = json_decode($result,true);
            foreach ($result as $item){

                $series = new CarBrandSeries();
                $series->id = $item['seriesId'];
                $series->name = $item['seriesName'];
                $series->brand_id = $brand['id'];

                $series->save();
                print_r('success!');
            }
//                print_r($brand->id );
        }


    }catch (\Exception $exception){
        echo $exception->getMessage();
    }
}


public function update(){
    try{
        $diandian = new DianDian();


        $data = [];
        $data['code']=2234;
        $result = $diandian->couponExchange(1,$data);
        print_r($result);


    }catch (\Exception $exception){
        echo $exception->getMessage();
    }
}



}
